### ISSUE TITLE
How about rollback event

### ISSUE THREAD

**Issue by Bongsakorn** [smariussorin/EventSourcedMicroservices#1]
Hi,
If there are problem between transaction, how does it rollback the data.

By the way, Thank you for your great example.
Pongsakorn

**Comment by smariussorin** [comment]
You could send a command to cancel the transaction to all microservices involved. Please use the documentation offered by https://github.com/adrai. Another example: http://cqrs.js.org/pages/saga.html by using timeout ('cancelOrder')
